import { Product, Category } from '../types';

// Images are served from /public/images — referenced as absolute URL paths
const MOCK_PRODUCTS: Product[] = [
  // ─── GEMSTONES ───────────────────────────────────────────────────────────
  {
    id: 'gem-1',
    name: 'Royal Blue Sapphire',
    slug: 'royal-blue-sapphire',
    description: 'A majestic Ceylon blue sapphire of exceptional clarity, radiating deep cornflower blue hues. Unheated and GIA certified.',
    originalPrice: 28000,
    price: 21500,
    images: ['/images/gemstone_1.png'],
    category: 'Gemstones',
    details: {
      origin: 'Ceylon',
      weight: '5.2 Carats',
      treatment: 'Unheated',
      shape: 'Oval',
      quality: 'Premium Grade',
    },
    stock: 5,
  },
  {
    id: 'gem-2',
    name: 'Zambian Emerald',
    slug: 'zambian-emerald',
    description: 'A vivid Zambian emerald with mesmerizing deep green color and natural inclusions. IGI certified.',
    originalPrice: 18000,
    price: 14200,
    images: ['/images/gemstone_2.png'],
    category: 'Gemstones',
    details: {
      origin: 'Zambia',
      weight: '4.1 Carats',
      treatment: 'Minor Oil',
      shape: 'Cushion',
      quality: 'AAA Grade',
    },
    stock: 3,
  },
  {
    id: 'gem-3',
    name: 'Burma Pigeon Blood Ruby',
    slug: 'burma-pigeon-blood-ruby',
    description: 'Rare Burmese ruby showcasing the legendary pigeon blood red — the rarest and most valuable ruby color in the world.',
    price: 42000,
    images: ['/images/gemstone_3.png'],
    category: 'Gemstones',
    details: {
      origin: 'Burma',
      weight: '3.1 Carats',
      treatment: 'Unheated',
      shape: 'Cushion',
      quality: 'AAA Grade',
    },
    stock: 2,
  },
  {
    id: 'gem-4',
    name: 'Yellow Sapphire (Pukhraj)',
    slug: 'yellow-sapphire-pukhraj',
    description: 'Bright Ceylon yellow sapphire, highly auspicious for Jupiter. Natural, unheated and lab certified for astrological use.',
    originalPrice: 26000,
    price: 19800,
    images: ['/images/gemstone_4.png'],
    category: 'Gemstones',
    details: {
      origin: 'Ceylon',
      weight: '6.4 Carats',
      treatment: 'Unheated',
      shape: 'Round',
      quality: 'Jyotish Grade',
    },
    stock: 7,
  },

  // ─── RUDRAKSHA ───────────────────────────────────────────────────────────
  {
    id: 'rud-1',
    name: '5 Mukhi Rudraksha Mala',
    slug: '5-mukhi-rudraksha-mala',
    description: 'Authentic 5 Mukhi Rudraksha mala (108+1 beads) from Nepal. Blessed for peace, clarity and spiritual growth.',
    price: 2800,
    images: ['/images/rudraksha_1.png'],
    category: 'Rudraksha',
    details: {
      origin: 'Nepal',
      mukhi: '5 Mukhi',
      quality: 'Lab Certified',
    },
    stock: 30,
  },
  {
    id: 'rud-2',
    name: '7 Mukhi Rudraksha',
    slug: '7-mukhi-rudraksha',
    description: 'Sacred 7 Mukhi Rudraksha representing Goddess Mahalakshmi. Attracts wealth, removes obstacles and blesses with prosperity.',
    originalPrice: 4500,
    price: 3600,
    images: ['/images/rudraksha_2.png'],
    category: 'Rudraksha',
    details: {
      origin: 'Nepal',
      mukhi: '7 Mukhi',
      quality: 'Lab Certified',
    },
    stock: 15,
  },
  {
    id: 'rud-3',
    name: '11 Mukhi Rudraksha',
    slug: '11-mukhi-rudraksha',
    description: 'Rare 11 Mukhi Rudraksha representing Lord Hanuman. Bestows courage, adventure and the wisdom of Lord Indra.',
    price: 8500,
    images: ['/images/rudraksha_3.png'],
    category: 'Rudraksha',
    details: {
      origin: 'Nepal',
      mukhi: '11 Mukhi',
      quality: 'Premium Certified',
    },
    stock: 8,
  },
  {
    id: 'rud-4',
    name: 'Gauri Shankar Rudraksha',
    slug: 'gauri-shankar-rudraksha',
    description: 'Two naturally joined Rudraksha beads — the most auspicious bead representing the union of Shiva and Parvati.',
    originalPrice: 15000,
    price: 11200,
    images: ['/images/rudraksha_4.png'],
    category: 'Rudraksha',
    details: {
      origin: 'Nepal',
      mukhi: 'Gauri Shankar',
      quality: 'Rare & Certified',
    },
    stock: 4,
  },

  {
    id: 'rud-5',
    name: 'Ganesh Rudraksha',
    slug: 'ganesh-rudraksha',
    description: 'The rare Ganesh Rudraksha with a naturally formed trunk-like protrusion. Bestows wisdom, intellect, and removes all obstacles.',
    price: 3200,
    images: ['/images/rudraksha_1.png'],
    category: 'Rudraksha',
    details: {
      origin: 'Nepal',
      mukhi: 'Ganesh',
      quality: 'Natural & Certified',
    },
    stock: 5,
  },
  {
    id: 'rud-6',
    name: '14 Mukhi Rudraksha',
    slug: '14-mukhi-rudraksha',
    description: 'Extremely rare 14 Mukhi Rudraksha (Devomani) ruled by Lord Hanuman. Bestows courage, sharp intuition and divine protection.',
    price: 21000,
    images: ['/images/rudraksha_4.png'],
    category: 'Rudraksha',
    details: {
      origin: 'Nepal',
      mukhi: '14 Mukhi',
      quality: 'Rare Certified',
    },
    stock: 2,
  },

  // ─── RINGS ───────────────────────────────────────────────────────────────
  {
    id: 'ring-1',
    name: 'Ruby Solitaire Gold Ring',
    slug: 'ruby-solitaire-gold-ring',
    description: 'A timeless 18k gold solitaire ring set with a vivid natural ruby. Handcrafted by master artisans with hallmark certification.',
    price: 52000,
    images: ['/images/ring_1.png'],
    category: 'Rings',
    details: {
      metal: '18k Gold',
      size: 'Ring Size 7',
      origin: 'Handcrafted, Jaipur',
      quality: 'BIS Hallmarked',
    },
    stock: 3,
  },
  {
    id: 'ring-2',
    name: 'Emerald Pave Diamond Ring',
    slug: 'emerald-pave-diamond-ring',
    description: 'Elegant platinum ring featuring a center Zambian emerald surrounded by pave-set natural diamonds. Statement luxury.',
    originalPrice: 95000,
    price: 78500,
    images: ['/images/ring_2.png'],
    category: 'Rings',
    details: {
      metal: 'Platinum 950',
      size: 'Ring Size 6',
      origin: 'Handcrafted, Mumbai',
      quality: 'IGI Certified',
    },
    stock: 1,
  },
  {
    id: 'ring-3',
    name: 'Blue Sapphire Cocktail Ring',
    slug: 'blue-sapphire-cocktail-ring',
    description: 'Bold and glamorous 22k gold cocktail ring featuring a large oval Ceylon blue sapphire with diamond halos.',
    originalPrice: 68000,
    price: 58000,
    images: ['/images/ring_3.png'],
    category: 'Rings',
    details: {
      metal: '22k Gold',
      size: 'Ring Size 7',
      origin: 'Handcrafted, Rajasthan',
      quality: 'Hallmarked',
    },
    stock: 2,
  },
  {
    id: 'ring-4',
    name: 'Yellow Sapphire Band Ring',
    slug: 'yellow-sapphire-band-ring',
    description: 'Astrological yellow sapphire ring in panchadhatu (five metals alloy). Ideal for Jupiter strengthening as per Vedic astrology.',
    price: 12500,
    images: ['/images/ring_4.png'],
    category: 'Rings',
    details: {
      metal: 'Panchadhatu',
      size: 'Adjustable',
      origin: 'Banaras, India',
      quality: 'Jyotish Grade',
    },
    stock: 20,
  },

  // ─── BRACELETS ───────────────────────────────────────────────────────────
  {
    id: 'brc-1',
    name: 'Amethyst Healing Bracelet',
    slug: 'amethyst-healing-bracelet',
    description: 'Natural amethyst crystal bracelet for spiritual protection, calm and enhanced intuition. Each bead is 10mm hand-polished.',
    price: 1800,
    images: ['/images/bracelet_1.png'],
    category: 'Bracelets',
    details: {
      origin: 'Brazil',
      weight: '10mm beads',
      quality: 'AA Grade',
    },
    stock: 40,
  },
  {
    id: 'brc-2',
    name: 'Lapis Lazuli 7 Chakra Bracelet',
    slug: 'lapis-lazuli-7-chakra-bracelet',
    description: 'Seven sacred gemstones combined into one powerful bracelet designed to align and balance all 7 chakras.',
    originalPrice: 3500,
    price: 2750,
    images: ['/images/bracelet_2.png'],
    category: 'Bracelets',
    details: {
      origin: 'Mixed Origins',
      weight: '8mm beads',
      quality: 'Chakra Certified',
    },
    stock: 25,
  },
  {
    id: 'brc-3',
    name: 'Tiger Eye Power Bracelet',
    slug: 'tiger-eye-power-bracelet',
    description: 'Golden Tiger Eye bracelet known for boosting courage, confidence and willpower. Strung on high-tensile elastic.',
    price: 1500,
    images: ['/images/bracelet_3.png'],
    category: 'Bracelets',
    details: {
      origin: 'South Africa',
      weight: '10mm beads',
      quality: 'AAA Grade',
    },
    stock: 50,
  },
  {
    id: 'brc-4',
    name: 'Rose Quartz Love Bracelet',
    slug: 'rose-quartz-love-bracelet',
    description: 'Premium rose quartz bracelet, the stone of unconditional love. Promotes self-love, compassion and emotional healing.',
    originalPrice: 2200,
    price: 1650,
    images: ['/images/bracelet_4.png'],
    category: 'Bracelets',
    details: {
      origin: 'Madagascar',
      weight: '8mm beads',
      quality: 'AA Grade',
    },
    stock: 35,
  },
];

const MOCK_CATEGORIES: Category[] = [
  { id: '1', name: 'Gemstones', slug: 'gemstones', image: '/images/gemstone_1.png' },
  { id: '2', name: 'Rudraksha', slug: 'rudraksha', image: '/images/rudraksha_1.png' },
  { id: '3', name: 'Rings', slug: 'rings', image: '/images/ring_1.png' },
  { id: '4', name: 'Bracelets', slug: 'bracelets', image: '/images/bracelet_1.png' },
];

export const api = {
  getProducts: async (): Promise<Product[]> => {
    return new Promise((resolve) => setTimeout(() => resolve(MOCK_PRODUCTS), 500));
  },
  getProductBySlug: async (slug: string): Promise<Product | undefined> => {
    return new Promise((resolve) => setTimeout(() => resolve(MOCK_PRODUCTS.find(p => p.slug === slug)), 300));
  },
  getCategories: async (): Promise<Category[]> => {
    return new Promise((resolve) => setTimeout(() => resolve(MOCK_CATEGORIES), 300));
  },
};
